import { StudyDeck } from "@/types/study";

export const DEMO_PRESETS: { id: string; name: string; icon: string; description: string; deck: StudyDeck }[] = [
  {
    id: "react-internals",
    name: "React Hooks & Fiber Architecture",
    icon: "Atom",
    description: "Deep dive into useEffect lifecycle, Fiber reconciliation, and concurrency.",
    deck: {
      id: "deck-demo-react",
      title: "Mastering React Hooks & Concurrent Rendering",
      topic: "React Architecture",
      summary: "Comprehensive flashcards and diagnostic quiz on React 18+ hooks, stale closures, Fiber scheduler, and memory management.",
      difficultyLevel: "intermediate",
      estimatedMinutes: 12,
      cards: [
        {
          id: "card-r-1",
          question: "What is a 'Stale Closure' in React and how does it happen in useEffect / useCallback?",
          answer: "A stale closure occurs when a callback or effect function captures variables from a past render cycle because the dependency array was omitted or incomplete. When state updates, the un-recreated callback continues referencing old lexical scope values.",
          hint: "Think about Javascript lexical scope captured at function declaration time.",
          difficulty: "hard",
          masteryStatus: "unseen",
        },
        {
          id: "card-r-2",
          question: "How does React Fiber achieve interruptible rendering and priority scheduling?",
          answer: "Fiber represents each component as a unit of work (Fiber node) in a linked list tree. The scheduler yields control to the browser event loop using MessageChannel / requestIdleCallback time-slicing, allowing high-priority user interactions to preempt background tree reconciliation.",
          hint: "Linked-list work units vs recursive call stack.",
          difficulty: "hard",
          masteryStatus: "unseen",
        },
        {
          id: "card-r-3",
          question: "When should you use `useLayoutEffect` instead of `useEffect`?",
          answer: "Use `useLayoutEffect` when you need to read DOM layout (e.g. element dimensions, scroll positions) and synchronously mutate the DOM before the browser paints, preventing visual screen flickering.",
          hint: "Timing relative to browser paint phase.",
          difficulty: "medium",
          masteryStatus: "unseen",
        },
        {
          id: "card-r-4",
          question: "Why does React require Hook calls to be top-level and unconditional?",
          answer: "React relies on a fixed call order to match hook state slots in the Fiber's internal singly linked list (`fiber.memoizedState`). Conditional calls would shift pointers, assigning wrong state to subsequent hooks.",
          hint: "Internal linked list indexed by execution sequence.",
          difficulty: "medium",
          masteryStatus: "unseen",
        },
        {
          id: "card-r-5",
          question: "What is the primary difference between `useMemo` and `useCallback`?",
          answer: "`useMemo` caches the calculated *result* of invoking a function (`() => computeValue(a, b)`), whereas `useCallback` caches the *function definition instance* itself (`(e) => handleClick(e)`). `useCallback(fn, deps)` is shorthand for `useMemo(() => fn, deps)`.",
          hint: "Memoizing returned value vs memoizing function reference.",
          difficulty: "easy",
          masteryStatus: "unseen",
        },
      ],
      quiz: [
        {
          id: "quiz-r-1",
          question: "Which hook executes synchronously AFTER all DOM mutations but BEFORE the browser paints to the screen?",
          options: ["useEffect", "useLayoutEffect", "useInsertionEffect", "useTransition"],
          correctIndex: 1,
          explanation: "useLayoutEffect fires synchronously after DOM mutation but before paint, making it suitable for layout measurements to prevent layout shift.",
        },
        {
          id: "quiz-r-2",
          question: "In React 18 Concurrent Mode, which API marks a state update as non-urgent so user inputs aren't blocked?",
          options: ["useDeferredValue & startTransition", "useRef.current", "flushSync", "useReducer"],
          correctIndex: 0,
          explanation: "startTransition and useDeferredValue let you prioritize urgent updates (like typing in an input) over transitions (like rendering a large chart).",
        },
        {
          id: "quiz-r-3",
          question: "What happens if a custom hook does not list a reactive state variable in its `useEffect` dependency array?",
          options: [
            "React throws an unrecoverable runtime crash",
            "The effect may access outdated state values (stale closure bug)",
            "The effect runs unconditionally on every millisecond",
            "The browser memory is instantly leaked"
          ],
          correctIndex: 1,
          explanation: "Omitting dependencies causes closures to retain old scope references, causing subtle synchronization and state update bugs.",
        },
        {
          id: "quiz-r-4",
          question: "What is the purpose of `useId` hook introduced in React 18?",
          options: [
            "To generate secure UUIDs for database records",
            "To generate stable, unique IDs across client and server hydration",
            "To track component render count",
            "To measure frame rendering latency"
          ],
          correctIndex: 1,
          explanation: "useId generates unique identifiers for accessibility attributes (like aria-describedby) that remain deterministic across SSR and client hydration.",
        },
      ],
      keyTakeaways: [
        "Fiber reconciles components using singly linked lists, enabling interruptible time-sliced rendering.",
        "Hooks rely on strict invocation order to index into `fiber.memoizedState`.",
        "`useLayoutEffect` blocks paint for synchronous measurement; `useEffect` runs asynchronously after paint.",
        "Always pass all referenced variables into dependency arrays or use functional state updaters (`prev => ...`) to eliminate stale closures.",
      ],
      createdAt: 1711000000000,
    },
  },
  {
    id: "web-perf",
    name: "Web Performance & Core Web Vitals",
    icon: "Gauge",
    description: "LCP, INP, CLS optimization, critical rendering path, and resource hints.",
    deck: {
      id: "deck-demo-webperf",
      title: "Core Web Vitals & Frontend Performance Engineering",
      topic: "Web Performance",
      summary: "Understand INP, LCP, CLS, resource prioritization, caching strategies, and layout thrashing.",
      difficultyLevel: "advanced",
      estimatedMinutes: 10,
      cards: [
        {
          id: "card-p-1",
          question: "What metric replaced FID (First Input Delay) as a Core Web Vital in March 2024, and how does it differ?",
          answer: "Interaction to Next Paint (INP) replaced FID. While FID measured only the input delay of the *first* interaction, INP assesses responsiveness across the *entire page lifecycle* measuring input delay, processing time, and presentation delay for all clicks, taps, and key presses.",
          hint: "Lifecycle responsiveness vs single first interaction.",
          difficulty: "hard",
          masteryStatus: "unseen",
        },
        {
          id: "card-p-2",
          question: "What is 'Layout Thrashing' and how do you prevent it?",
          answer: "Layout thrashing occurs when JavaScript repeatedly alternates between reading geometry properties (e.g. `offsetWidth`, `getBoundingClientRect`) and writing styles (e.g. `element.style.width`), forcing the browser to perform synchronous layouts. Prevent by batching all reads before all writes or using `requestAnimationFrame`.",
          hint: "Interleaving style writes and DOM layout reads.",
          difficulty: "medium",
          masteryStatus: "unseen",
        },
        {
          id: "card-p-3",
          question: "How does `fetchpriority='high'` benefit Largest Contentful Paint (LCP)?",
          answer: "It signals the browser preload scanner to prioritize fetching the critical LCP image over other discoverable subresources (like scripts or non-hero images), drastically reducing the Resource Load Delay phase.",
          hint: "Browser resource scheduling priority.",
          difficulty: "medium",
          masteryStatus: "unseen",
        },
      ],
      quiz: [
        {
          id: "quiz-p-1",
          question: "What is the recommended 'Good' threshold for Interaction to Next Paint (INP)?",
          options: ["<= 200 milliseconds", "<= 50 milliseconds", "<= 500 milliseconds", "<= 1000 milliseconds"],
          correctIndex: 0,
          explanation: "Google's Core Web Vitals threshold categorizes INP below or at 200ms as 'Good', 200-500ms as 'Needs Improvement', and over 500ms as 'Poor'.",
        },
        {
          id: "quiz-p-2",
          question: "Which CSS property can eliminate unexpected Cumulative Layout Shift (CLS) when loading responsive images?",
          options: ["aspect-ratio", "content-visibility: auto", "will-change: transform", "box-sizing: border-box"],
          correctIndex: 0,
          explanation: "Defining explicit width/height or the `aspect-ratio` CSS property reserves space in the layout before image bits download, eliminating CLS.",
        },
        {
          id: "quiz-p-3",
          question: "What is the primary cause of high Presentation Delay in the INP breakdown?",
          options: [
            "Complex DOM tree restructuring and heavy compositing/rendering on the main thread",
            "Slow DNS lookup time",
            "Uncompressed HTTP response bodies",
            "Slow disk I/O on the user's hard drive"
          ],
          correctIndex: 0,
          explanation: "Presentation delay happens between the callback completion and browser painting next frame, usually caused by huge DOM recalculations and paint complexity.",
        },
      ],
      keyTakeaways: [
        "INP tracks the 98th percentile of all interaction latencies throughout the entire session.",
        "LCP breaks down into Time to First Byte (TTFB), Resource Load Delay, Resource Load Time, and Element Render Delay.",
        "Always set `aspect-ratio` or explicit dimensions on media to maintain 0.0 CLS score.",
      ],
      createdAt: 1711000000000,
    },
  },
  {
    id: "system-design",
    name: "System Design & Distributed Scalability",
    icon: "Network",
    description: "CAP Theorem, caching strategies, rate limiting, and database partitioning.",
    deck: {
      id: "deck-demo-sysdesign",
      title: "Distributed Systems & Scalable Architecture",
      topic: "System Design",
      summary: "Explore consistent hashing, write-through vs write-back caching, consensus, and horizontal scaling.",
      difficultyLevel: "intermediate",
      estimatedMinutes: 15,
      cards: [
        {
          id: "card-s-1",
          question: "Explain the difference between Write-Through and Write-Back (Write-Behind) caching.",
          answer: "In Write-Through, data is written synchronously to both the cache and underlying database before acknowledging success, guaranteeing high consistency at the cost of higher write latency. In Write-Back, data is written to the cache immediately and asynchronously flushed to the database in batches, providing low write latency with risk of data loss on cache failure.",
          hint: "Synchronous dual-write vs asynchronous background persistence.",
          difficulty: "medium",
          masteryStatus: "unseen",
        },
        {
          id: "card-s-2",
          question: "What problem does Consistent Hashing solve in distributed caching clusters?",
          answer: "In traditional hash(key) % N sharding, adding or removing a node requires remapping almost all keys (K * (N-1)/N keys). Consistent Hashing places nodes and keys on a virtual ring (0 to 2^32-1). Adding/removing a node only redistributes K/N keys on average without mass cache eviction.",
          hint: "Minimizing key movement during node addition or deletion.",
          difficulty: "hard",
          masteryStatus: "unseen",
        },
      ],
      quiz: [
        {
          id: "quiz-s-1",
          question: "According to the CAP theorem, during a network partition (P), a distributed system must choose between which two properties?",
          options: ["Consistency and Availability", "Concurrency and Parallelism", "Atomicity and Durability", "Speed and Throughput"],
          correctIndex: 0,
          explanation: "When network nodes cannot communicate (Partition), the system can either reject requests to preserve Consistency (CP) or accept writes on divergent nodes sacrificing Consistency for Availability (AP).",
        },
        {
          id: "quiz-s-2",
          question: "Which rate limiting algorithm allows bursts of requests up to a maximum capacity while processing at a steady average rate?",
          options: ["Token Bucket", "Fixed Window Counter", "Sliding Log", "Round Robin"],
          correctIndex: 0,
          explanation: "Token Bucket refills tokens at a constant rate and allows bursts up to bucket capacity as long as sufficient tokens exist.",
        },
      ],
      keyTakeaways: [
        "Consistent hashing minimizes cache misses during horizontal scaling events using virtual nodes.",
        "Choose CP systems (like ZooKeeper/Spanner) for financial data and AP systems (like Cassandra/DynamoDB) for high-availability feeds.",
        "Use Redis/Memcached with TTL and cache stampede protection (probabilistic early expiration) for hot keys.",
      ],
      createdAt: 1711000000000,
    },
  },
];
